const oldNewMap: Record<string, string[]> = {
    '--color-dark-indigo': [
        '--color-light-text-primary',
        '--color-light-bg-primary-inverted',
        '--color-light-border-key',
        '--color-light-graphic-primary',
    ],
    '--color-dark-indigo-60-flat': [
        '--color-light-text-secondary',
        '--color-light-border-tertiary-inverted',
        '--color-light-graphic-secondary',
    ],
    '--color-dark-indigo-30-flat': [
        '--color-light-text-tertiary',
        '--color-light-border-secondary-inverted',
        '--color-light-graphic-tertiary',
    ],
    '--color-dark-indigo-15-flat': [
        '--color-light-text-disabled',
        '--color-light-bg-quaternary',
        '--color-light-border-primary',
        '--color-light-graphic-quaternary',
    ],
    '--color-dark-indigo-10-flat': ['--color-light-bg-tertiary', '--color-light-border-secondary'],
    '--color-dark-indigo-07-flat': ['--color-light-specialbg-component'],
    '--color-dark-indigo-05-flat': [
        '--color-light-bg-secondary',
        '--color-light-border-tertiary',
        '--color-light-graphic-primary-inverted',
    ],
    '--color-red-brand': [
        '--color-light-text-accent',
        '--color-light-bg-accent',
        '--color-light-border-accent',
        '--color-light-graphic-accent',
    ],
    '--color-red-brand-85-flat': [],
    '--color-red-brand-70-flat': [],
    '--color-red-brand-50-flat': [],
    '--color-red-brand-30-flat': [],
    '--color-red-brand-20-flat': [],
    '--color-red-brand-10-flat': ['--color-light-bg-negative-muted'],
    '--color-red-brand-05-flat': ['--color-light-bg-negative-muted'],
    '--color-red-dark': ['--color-light-text-negative', '--color-light-graphic-negative'],
    '--color-red-error': ['--color-light-text-negative', '--color-light-graphic-negative'],
    '--color-green-text': ['--color-light-text-positive'],
    '--color-green-text-60-flat': [],
    '--color-green-done': ['--color-light-graphic-positive'],
    '--color-green-done-20-flat': [],
    '--color-green-done-10-flat': ['--color-light-bg-positive-muted'],
    '--color-green-done-05-flat': ['--color-light-bg-positive-muted'],
    '--color-blue-action': [],
    '--color-blue-swipe-a': [],
    '--color-blue-swipe-b': [],
    '--color-blue-swipe-c': [],
    '--color-blue-link-mobile': [
        '--color-light-text-link',
        '--color-light-graphic-link',
        '--color-light-border-link',
    ],
    '--color-blue-link-mobile-10-flat': ['--color-light-bg-info'],
    '--color-blue-link-web': [
        '--color-light-text-link',
        '--color-light-graphic-link',
        '--color-light-border-link',
    ],
    '--color-sand': ['--color-static-graphic-sand'],
    '--color-lavender': ['--color-static-graphic-lavender'],
    '--color-amethyst': ['--color-static-graphic-amethyst'],
    '--color-black': [],
    '--color-black-60-flat': ['--color-light-bg-overlay'],
    '--color-black-30-flat': [],
    '--color-black-10-flat': [],
    '--color-white': [
        '--color-light-text-primary-inverted',
        '--color-light-bg-primary',
        '--color-light-border-key-inverted',
    ],
    '--color-bg-corporate': ['--color-static-corpbg-primary'],
    '--color-bg-corporate-90-flat': ['--color-static-corpbg-secondary'],
    '--color-bg-corporate-60-flat': ['--color-static-corpbg-tertiary'],
    '--color-bg-corporate-30-flat': ['--color-static-corpbg-neutral'],
    '--color-light-blue': ['--color-static-local-light-blue'],
    '--color-dark-indigo-60': [
        '--color-light-text-secondary-transparent',
        '--color-light-border-tertiary-inverted',
        '--color-light-graphic-secondary',
    ],
    '--color-dark-indigo-30': [
        '--color-light-text-tertiary',
        '--color-light-border-secondary-inverted',
        '--color-light-graphic-tertiary',
    ],
    '--color-dark-indigo-15': ['--color-light-text-disabled'],
    '--color-dark-indigo-10': ['--color-light-bg-tertiary', '--color-light-border-secondary'],
    '--color-dark-indigo-07': ['--color-light-specialbg-component'],
    '--color-dark-indigo-05': [
        '--color-light-bg-secondary',
        '--color-light-border-tertiary',
        '--color-light-graphic-primary-inverted',
    ],
    '--color-red-brand-85': [],
    '--color-red-brand-70': [],
    '--color-red-brand-50': [],
    '--color-red-brand-30': [],
    '--color-red-brand-20': [],
    '--color-red-brand-10': ['--color-light-bg-negative-muted'],
    '--color-green-text-60': [],
    '--color-green-done-20': [],
    '--color-green-done-10': ['--color-light-bg-positive-muted'],
    '--color-green-done-05': ['--color-light-bg-positive-muted'],
    '--color-blue-link-mobile-10': ['--color-light-bg-info'],
    '--color-black-60': ['--color-light-bg-overlay'],
    '--color-black-30': [],
    '--color-black-10': [],
    '--color-white-60': ['--color-light-text-secondary-inverted', '--color-light-bg-opaque'],
    '--color-white-30': ['--color-light-text-tertiary-inverted'],
    '--color-white-10': [],
    '--color-bg-corporate-90': ['--color-static-corpbg-secondary'],
    '--color-bg-corporate-60': ['--color-static-corpbg-tertiary'],
    '--color-bg-corporate-30': ['--color-static-corpbg-neutral'],
};

export default oldNewMap;
