name: Create new library package

on:
    workflow_dispatch:
      inputs:
        channel:
          description: 'NPM channel to use'
          required: true
          default: 'next'
    push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create new version
        run: |
            yarn install --immutable
            yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORK_SPACE: ${{ github.workspace }}
          CI: true
