name: Create new library package

on:
    workflow_dispatch:
    push:
      branches:
        - master
        - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
            token: ${{ secrets.GH_TOKEN }}
      - name: create new version
        run: |
            yarn install --immutable
            yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          WORK_SPACE: ${{ github.workspace }}
          CI: true
